export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-bold text-gold-gradient">Terms of Service</h1>
        <p className="text-gray-400">Last updated: February 6, 2026</p>
      </div>

      <div className="glass-card p-8 space-y-8 text-gray-300 leading-relaxed">

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using KinForge (kinforge.xyz), including interacting with our smart
            contracts on BNB Chain, you agree to be bound by these Terms of Service. If you do not
            agree to these terms, please do not use our service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">2. Service Description</h2>
          <p>
            KinForge is a decentralized application that provides Non-Fungible Agent (NFA) tokens
            on the BNB Chain blockchain. Our services include:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 mt-2">
            <li>Minting and managing AI-powered NFT agents</li>
            <li>Fusion (breeding) system to create offspring agents</li>
            <li>AI-powered dialogue with personalized agent personalities</li>
            <li>Agent memory, learning, and on-chain growth verification</li>
            <li>NFT gallery, lineage tree, and metadata browsing</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">3. Wallet Connection</h2>
          <p>
            To use certain features of KinForge, you must connect a compatible blockchain wallet
            (e.g., MetaMask, WalletConnect-compatible wallets). By connecting your wallet, you
            authorize the application to:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 mt-2">
            <li>Read your public wallet address for identity verification</li>
            <li>Request transaction signatures for minting, fusion, and other on-chain operations</li>
            <li>Verify token ownership for AI chat access</li>
          </ul>
          <p className="mt-2">
            We never have access to your private keys. All transactions require your explicit
            approval through your wallet application.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">4. NFT Ownership</h2>
          <p>
            When you mint or acquire a KinForge NFT, you own the token on the blockchain. Ownership
            grants you:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 mt-2">
            <li>The right to transfer, sell, or trade the NFT on secondary markets</li>
            <li>Access to AI dialogue with your agent (owner-only feature)</li>
            <li>Access to your agent&apos;s memories and learning history</li>
            <li>The ability to participate in fusion to create offspring</li>
          </ul>
          <p className="mt-2 text-yellow-400/80">
            Note: Sealed tokens (from Seal-mode fusion) cannot be transferred or traded.
            This restriction is enforced at the smart contract level.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">5. Digital Collectibles Disclaimer</h2>
          <p>
            KinForge NFTs are digital collectibles. They are <strong>not</strong> investment products,
            securities, or financial instruments. We make no guarantees regarding:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 mt-2">
            <li>Future value or price appreciation of any NFT</li>
            <li>Liquidity or ability to resell on secondary markets</li>
            <li>Continued availability of off-chain services (AI chat, images, metadata hosting)</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">6. AI Chat Service</h2>
          <p>
            The AI dialogue feature is powered by third-party AI models. By using the chat feature,
            you acknowledge that:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 mt-2">
            <li>AI responses are generated by machine learning models and may not always be accurate</li>
            <li>Chat content is processed by third-party AI providers (OpenAI)</li>
            <li>Agent personalities are simulated and do not represent real entities</li>
            <li>We reserve the right to moderate or filter inappropriate content</li>
            <li>The AI chat service may be temporarily unavailable due to maintenance or provider issues</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">7. Fusion System</h2>
          <p>
            The fusion system uses a commit-reveal mechanism to ensure fairness. By participating
            in fusion, you acknowledge that:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 mt-2">
            <li>Offspring traits are determined algorithmically and cannot be predetermined</li>
            <li>In Burn-to-Mint mode, parent tokens are permanently destroyed</li>
            <li>In Seal mode, parent tokens are permanently sealed and cannot be transferred</li>
            <li>Fusion fees are non-refundable once the transaction is confirmed</li>
            <li>Gas fees for blockchain transactions are paid by the user</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">8. Smart Contract Risks</h2>
          <p>
            Our smart contracts are deployed on BNB Chain. While we have taken measures to ensure
            their security, you acknowledge that:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 mt-2">
            <li>Smart contracts carry inherent risks including potential bugs or vulnerabilities</li>
            <li>Blockchain transactions are irreversible</li>
            <li>Network congestion may affect transaction timing and costs</li>
            <li>You are responsible for verifying transaction details before signing</li>
          </ul>
          <p className="mt-2">
            Our smart contracts are verified and publicly viewable on{' '}
            <a href="https://bscscan.com/address/0x713Be3D43c5DdfE145215Cd366c553c75A06Ce7f#code" target="_blank" rel="noopener noreferrer" className="text-amber-400 hover:text-amber-300">
              BSCScan
            </a>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">9. Prohibited Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-2 ml-2 mt-2">
            <li>Use the service for any illegal or unauthorized purpose</li>
            <li>Attempt to exploit, hack, or compromise our smart contracts or servers</li>
            <li>Use automated bots to manipulate minting or fusion processes</li>
            <li>Engage in fraudulent activity including market manipulation</li>
            <li>Use the AI chat feature to generate harmful, abusive, or illegal content</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">10. Limitation of Liability</h2>
          <p>
            KinForge is provided &quot;as is&quot; without warranties of any kind. To the maximum extent
            permitted by law, we shall not be liable for any direct, indirect, incidental, or
            consequential damages arising from your use of the service, including but not limited to
            loss of funds, data, or digital assets.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">11. Service Modifications</h2>
          <p>
            We reserve the right to modify, suspend, or discontinue any part of the service at any
            time. On-chain data (NFT ownership, metadata hashes) will remain on the blockchain
            regardless of service availability.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">12. Changes to Terms</h2>
          <p>
            We may update these Terms of Service from time to time. Continued use of the service
            after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-amber-400 mb-3">13. Contact</h2>
          <p>
            For questions about these Terms, please reach out via our{' '}
            <a href="https://x.com/kinforge_lab" target="_blank" rel="noopener noreferrer" className="text-amber-400 hover:text-amber-300">
              X (Twitter)
            </a>{' '}
            or{' '}
            <a href="https://github.com/KinForgeLab/kinforge" target="_blank" rel="noopener noreferrer" className="text-amber-400 hover:text-amber-300">
              GitHub
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
